name: Version Update and Push

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # To allow manual triggering

jobs:
  version-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit any unstaged changes
      run: |
        git add .
        git commit -m "Auto-commit before pull" || echo "No changes to commit"
    
    - name: Pull the latest changes from main
      run: |
        git pull --rebase https://$PAT@github.com/OWNER/REPO.git main

    - name: Update version
      run: |
        echo ${{ github.sha }} > VERSION
        cat VERSION

    - name: Commit and push VERSION file
      env:
        PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git add VERSION
        git commit -m "Update version to ${{ github.sha }}"
        git push https://$PAT@github.com/OWNER/REPO.git HEAD:main
