name: Dockerize and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate a version tag using the GitHub SHA or run number
      - name: Set version tag
        id: vars
        run: echo "VERSION_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build and push Docker image with unique tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            shree314/bitemeals:latest
            shree314/bitemeals:${{ env.VERSION_TAG }}

      # Update the VERSION file with the new tag
      - name: Update VERSION file
        run: echo "${{ env.VERSION_TAG }}" > VERSION

      # Commit and push the updated VERSION file to the repository
      - name: Commit and push VERSION file
        env:
          PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase https://$PAT@github.com/Shree-1729/bitemeals.git main
          git add VERSION
          git commit -m "Update version to ${{ env.VERSION_TAG }}"
          git push https://$PAT@github.com/Shree-1729/bitemeals.git HEAD:main
